#!/bin/bash
set -euo pipefail
BUILD_IMAGE="quay.io/mariadb-foundation/bb-worker:debian13"


# A separate .tgz is needed for the child builders in Buildbot
# because test/ and libmariadb/ are not packed in the source tarball generated by CMake
# each builder will download the .tgz from ci.mariadb.org/connectors/#this_builder_build_number#
# avoiding a `git clone` and `git submodule update` per child-builder.

echo "--------------------------------------------------------------"
echo "Get source"
echo "--------------------------------------------------------------"
docker run \
  -e GIT_REPO=$GIT_REPO \
  -e GIT_COMMIT=$GIT_COMMIT \
  -e GIT_BRANCH=$GIT_BRANCH \
  -e SOURCE_DIR=$SOURCE_DIR \
  -e TGZ_TARGET=$VOLUME_MOUNT_POINT \
  -v $VOLUME_NAME:$VOLUME_MOUNT_POINT \
  -w $VOLUME_MOUNT_POINT \
  --network $NETWORK_NAME \
  --rm \
  --name $CONTAINER_NAME \
  $BUILD_IMAGE \
  bash -ec '
    mkdir -p $SOURCE_DIR
    cd $SOURCE_DIR
    git clone -b $GIT_BRANCH $GIT_REPO .
    git reset --hard $GIT_COMMIT
    git submodule update --init --recursive
    SHA=$(git rev-parse --short=12 HEAD)
    OUT="$TGZ_TARGET/odbc-src-with-cc-tests-${SHA}.tgz"
    tar --exclude-vcs -czf "$OUT" .

    cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_OPENSSL=OFF -DGIT_BUILD_SRCPKG=1 .
    mv *.tar.gz "$TGZ_TARGET"
    rm -rf *
  '